### PR TITLE
Add ICON release 2.6.3.0 (pgi)

### PR DESCRIPTION
**Pull request by mjaehn**

### CODE REVIEW

**Comment by jonasjucker** [comment]
@mjaehn The standard deviation for the PGI ref looks a bit high. Even T_2M is really off.

Was the spinoff set correctly? Or could anything else influence the results?

**Comment by jonasjucker** [comment]
Could also be a bug, since for PGI none of the techincal tests validated

**Comment by mjaehn** [comment]
I will check this right now

**Comment by mjaehn** [comment]
I didn't delete the 2012 data. Another PR will be opened

**Pull request closed without merging**
